#!/bin/bash
# optimize_molecules.job
# Step 2: MMFF optimize conformers and cluster by RMSD.
#
# Usage:
#   sbatch optimize_molecules.job \
#     --sdf_in /path/to/conformer_mols.sdf \
#     --conf 20 \
#     --out_dir /path/to/output

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=36
#SBATCH --mem=59GB
#SBATCH --time=8:00:00
#SBATCH --account=qcb_640
#SBATCH --partition=main

module purge
module load gcc/11.3.0
module load python/3.9.12
module load conda

conda init bash
source ~/.bashrc
source activate project_1

mkdir -p log

python optimize_molecules.py "$@" \
    1> log/optimize_molecules.$SLURM_JOB_ID.log \
    2> log/optimize_molecules.$SLURM_JOB_ID.err
